### ISSUE TITLE
listing packages required for octave, as requested.

### ISSUE THREAD

**Issue by snapek** [moeller0/ATM_overhead_detector#1]
This was on a Sid system, up-to-date before I went to install 'octave' with apt-get.  Versions may differ for Jessie.

I can also run this on a Jessie machine (on a raspberrypi) if desired.

The following NEW packages will be installed:
  aglfn gnuplot-data gnuplot-tex gnuplot-x11 libamd2.4.1 libarpack2 libcamd2.4.1 libccolamd2.9.1 libcholmod3.0.6 libcolamd2.9.1
  libcxsparse3.1.4 libfltk-gl1.3 libfltk1.3 libgl2ps0 libglpk36 libgraphicsmagick++-q16-12 libgraphicsmagick-q16-3 libhdf5-10
  libmagick++-6.q16-5v5 liboctave3v5 libopenblas-base libosmesa6 libplot2c2 libpstoedit0c2a libqrupdate1 libqscintilla2-12v5
  libqscintilla2-l10n libsuitesparseconfig4.4.5 libumfpack5.7.1 octave octave-common octave-info pstoedit

**Comment by snapek** [comment]
had issues getting the .m script to run on the Sid machine, so I'm compiling Octave 4.0.0 on the raspberry pi running Jessie.  Will keep note of what additional packages were required to build it, and report back.

Hi snapek,

What issues did have on the sid machine (could you post the output of octaves terminal/command window, please. Akso which version of octave comes with sid?

Since I will not be able supporting people in getting octave up and running, I am more concerned which additional octave-packages are required to run ATM_overhead_detector.m, I believe this is down to the statistics package which is optional so hopefully nothing required besides a standard octave >= 3.8 or so installation (that is configured with working graphics output).

Thanks for 
your help

**Comment by moeller0** [comment]
So on my system that used to work
octave:1> pkg list
Package Name   | Version | Installation directory
---------------+---------+-----------------------
        image  |  1.0.15 | /Users/moeller/octave/image-1.0.15
           io  |  2.2.11 | /opt/local/share/octave/packages/io-2.2.11
miscellaneous  |   1.1.0 | /Users/moeller/octave/miscellaneous-1.1.0
   statistics  |   1.2.4 | /opt/local/share/octave/packages/statistics-1.2.4

The statistics package is only required for the geomean function and will now attempt to load the statistics pkg intelligently, that is will just not show geomean based plots...

**Comment by moeller0** [comment]
I tried to improve the octave compatibility a bit, but there are still some issues, Like parsing the text files takes ages, but unlike in matlab, octave will only display all intermediary output at once but only after finishing, so it seems to be stuck forever...

**Comment by moeller0** [comment]
So, if you have octave setup to use gnu plot for its output, hopefully all requirements are met. I assume that the exact packages that need to be installed in different linux distributions to get octave installed and configured for gbuplot output will not be identical, but hopefully ATM_overhead_detector.m will work once the octave works.

**Comment by snapek** [comment]
Having never used or set up Octave before, I'm still figuring things out. 

That said, what are the chances you could do the output for me, using my ping results?

https://drive.google.com/file/d/0B7Z3K8tUGmJDeEVlamgtNXRxSlU/view?usp=sharing

**Comment by moeller0** [comment]
Hi snapek,

On Dec 4, 2015, at 20:16 , snapek notifications@github.com wrote:

> Having never used or set up Octave before, I'm still figuring things out.

```
Which is great! I would not be amazed if the biggest issue is the dog slow parser wich might take more than 10 minutes under octave...
```

> That said, what are the chances you could do the output for me, using my ping results?

```
Ah, no problem, here is part of the text output with #comments:
```

[...]
Parsing took: 254.5167 seconds. #so this took 4 minutes of parsing with matlab, probably more with octave, and matlab at least gives intermediate progress reports...
Minimum size of ping payload used: 16 bytes.
Saved current figure to: /path/ping_sweep__20151204_082530_data.pdf
lower bound estimate for one ATM cell RTT based of specified up and downlink is 0.61412 ms. #this is bogus, I ned to change the message
estimate for one ATM cell RTT based on linear fit of the ping sweep data is 0.61412 ms.
Best staircase fit cumulative difference is: 5.4456
Best linear fit cumulative difference is: 20.1161
Quantized ATM carrier LIKELY (cummulative residual: stair fit 5.4456 linear fit 20.1161 # the residuals is basically the simple sum of the absolute differences between data and fitting function, so stair wins hands down, you have an ATM link ;)
remaining ATM cell length after ICMP header is 17 bytes.
ICMP RTT of a single ATM cell is 0.58956 ms.

Estimated overhead preceding the IP header: 36 bytes
Saved current figure to: /path/ping_sweep__20151204_082530_results.pdf

According to http://ace-host.stuart.id.au/russell/files/tc/tc-atm/
36 bytes overhead indicate
Connection: Bridged, LLC/SNAP+FCS RFC-1483/2684
Protocol (bytes): Ethernet Header (14), Ethernet PAD [8](0), Ethernet Checksum (4), ATM LLC (3), ATM SNAP (5), ATM pad (2), ATM AAL5 SAR (8) : Total 36
OR
Connection: PPPoE, VC/Mux+FCS RFC-2684
Protocol (bytes): PPP (2), PPPoE (6), Ethernet Header (14), Ethernet PAD [8](0), Ethernet Checksum (4), ATM pad (2), ATM AAL5 SAR (8) : Total 36
 [...] 
ATM_overhead_detector took: 277.1937 seconds.
Done�

If you want to use this knowledge with sqm-scripts set �Which link layer to account for:� to ATM, and put 36 into �Per Packet Overhead (byte):�. Now most likely the kernel will have auto-added 14 bytes already (but that depends on the interface) so you might get away with putting 36-14 = 22 into the overhead field.

I will paste your data and result plot to the wiki� see: https://github.com/moeller0/ATM_overhead_detector/wiki/more-examples

Best Regards

**Comment by snapek** [comment]
Thank you.  I will try running with 22 for the overhead, using cake/layer_cake.  I'll let you know how it goes :)

**Comment by moeller0** [comment]
Hi Snapek,

thanks for the package list, since I realize I can not really help with octave installation issues (due to lack of experience) anyway, and I believe that this project does not require anything besides the actual octave package installed I am going to close this issue, Fell free to re-open if you disagree.

Best Regards
