### ISSUE TITLE
Test run against DSLAM on PPPoA/VCmux

### ISSUE THREAD

**Issue by hoverdead** [moeller0/ATM_overhead_detector#2]
ATM overhead detector worked as expected.
Good job!
![fig 2](https://user-images.githubusercontent.com/29546234/27294123-2757e87a-5521-11e7-9264-88a813155c71.png)
![fig 1](https://user-images.githubusercontent.com/29546234/27294124-27788f26-5521-11e7-8f60-2a6c14c2a8a5.png)

**Comment by moeller0** [comment]
Excellent, thanks a lot!
