### ISSUE TITLE
ATM overhead detector results

### ISSUE THREAD

**Issue by Strasedon** [moeller0/ATM_overhead_detector#3]
Quantized ATM carrier LIKELY (cumulative residual: stair fit 7.9245 linear fit 26.8822)

My ADSL provider is CenturyLink, the modem says transport mode is ATM and the "Service Mode" or "Encapsulation" is "ATM - LLC Bridged".

I tested against the first hop after the router instead of Google's DNS server and the estimated overhead preceding the IP header is 32 bytes.

**Comment by moeller0** [comment]
Great! Thanks, already added to the wiki
