### ISSUE TITLE
non-ATM link results

### ISSUE THREAD

**Issue by hoverdead** [moeller0/ATM_overhead_detector#4]
Happy new year!
Here's another run on a different ISP; this time it's PPPoE/PTM (VDSL2).
Cheers!
![fig 1](https://user-images.githubusercontent.com/29546234/34685276-828edb84-f4b0-11e7-8fd2-11fadfb057d8.png)
![fig 2](https://user-images.githubusercontent.com/29546234/34685278-82bda108-f4b0-11e7-8f56-c7ba0f095f94.png)

**Comment by hoverdead** [comment]
@moeller0 ???

**Comment by moeller0** [comment]
Hi and thanks,

I guess I monitor the issues way to irregular.

But this is exiting in that it looks like there is another step process going on, maybe of 64 bytes. This is the first time I see something like that for a ptm link. Thanks again
