### ISSUE TITLE
my own ATM Overhead Detector results, as requested

### ISSUE THREAD

**Issue by FuzzyQuils** [moeller0/ATM_overhead_detector#6]
Quantized ATM carrier LIKELY (cumulative residual: stair fit 3.2921 linear fit 18.8933)
ADSL Provider: Dodo Australia, PPPoE LLC, ADSL2 running at 1430/385 kbps
Estimated overhead preceding the IP header is 40 bytes. Tested using Google DNS

**Comment by moeller0** [comment]
Thanks a lot!
