### ISSUE TITLE
A1 - result 21. January 2022

### ISSUE THREAD

**Issue by aversario** [moeller0/ATM_overhead_detector#7]
ISP - A1

PINGPERIOD=0.005
PINGSPERSIZE=15000

ADSL2plus

![ping_sweep__20220120_000843_results](https://user-images.githubusercontent.com/5672163/154935696-60f34052-78a4-4ef8-b12f-909827bd955c.png)

Minimum size of ping payload used: 16 bytes.

lower bound estimate for one ATM cell RTT based of specified up and downlink is 0.42885 ms.
estimate for one ATM cell RTT based on linear fit of the ping sweep data is 0.42885 ms.
Starting brute-force search for optimal stair fit, might take a while...
Best staircase fit cumulative difference is: 2.4513
Best linear fit cumulative difference is: 16.0693
Quantized ATM carrier LIKELY (cummulative residual: stair fit 2.4513 linear fit 16.0693
remaining ATM cell length after ICMP header is 13 bytes.
ICMP RTT of a single ATM cell is 0.39883 ms.
 
Estimated overhead preceding the IP header: 40 bytes

**Comment by moeller0** [comment]
Thanks this looks pretty decent, unfortunately the font in the figure title is so large that the relevant numbers are not all visible. Could you please copy and paste the full "Estimated RTT..." title here into this issue, I need the number for the linear fit...

**Comment by aversario** [comment]
> .

I've edited OP, thank you for your effort. Is there any other info I could provide?
