### ISSUE TITLE
Results when testing my ISP DSLAM

### ISSUE THREAD

**Issue by kaxapo** [moeller0/ATM_overhead_detector#8]
Hello as you asked here are two graphs of me testing my isp dslam and the isp router after it with a repetition of 150 on the shell:

Router after DSLAM:
![routerafterdslam](https://user-images.githubusercontent.com/83574834/158402246-ebffb234-169d-4aae-93f0-277b7d1af41a.png)

DSLAM:
![dslam](https://user-images.githubusercontent.com/83574834/158403097-97833205-ab1c-425d-9317-1b79b95d9b43.png)

**Comment by moeller0** [comment]
Thanks!
